export { default as AboutPage } from './AboutPage.vue'
export { default as HomePage } from './TelasEmanuel.vue'
export { default as LoginPage } from './LoginPage.vue'
export { default as NewAccount } from './NewAccount.vue'
export { default as NotFound } from './NotFound.vue'
export { default as HomeTienda } from './HomeTienda.vue'
export { default as HomeTapiceria } from './HomeTapiceria.vue'
export { default as CategoriesPage } from './CategoriesPage.vue'