export { default as AboutPage } from './AboutPage.vue'
export { default as HomePage } from './HomePage.vue'
export { default as ReceptionPage } from './ReceptionPage.vue'
export { default as LoginPage } from './LoginPage.vue'
export { default as CategoriesPage } from './CategoriesPage.vue'
export { default as NewAccount } from './NewAccount.vue'
export { default as NotFound } from './NotFound.vue'
export { default as TelasEmanuel } from './TelasEmanuel.vue'